apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "config-system.fullname" . }}-nginx-config
data:
  nginx.conf: |-
    upstream web_services {
        server {{ include "config-system.fullname" . }}-web-service:8080;
    }
    upstream worker_services {
        server {{ include "config-system.fullname" . }}-worker-service:8080;
    }
    
    server {
        listen 8110;
        location / {
            proxy_pass http://web_services;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        location /status {
            proxy_pass http://web_services/status;
            proxy_set_header Host $host;
        }
        location /worker_status {
            proxy_pass http://worker_services/status;
            proxy_set_header Host $host;
        }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "config-system.fullname" . }}-nginx
spec:
  selector:
    matchLabels:
      app: {{ include "config-system.name" . }}
      component: nginx
  template:
    metadata:
      labels:
        app: {{ include "config-system.name" . }}
        component: nginx
    spec:
      containers:
        - name: nginx
          image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}"
          ports:
            - containerPort: 8110
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: nginx.conf
      volumes:
        - name: nginx-config
          configMap:
            name: {{ include "config-system.fullname" . }}-nginx-config

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "config-system.fullname" . }}-nginx
spec:
  type: {{ .Values.nginx.service.type }}
  ports:
    - port: {{ .Values.nginx.service.port }}
      targetPort: {{ .Values.nginx.service.targetPort }}
  selector:
    app: {{ include "config-system.name" . }}
    component: nginx
